query ProjectByName($name: String!) {
  projectByName(name: $name) {
    id
    name
    gitUrl
    productionEnvironment
    environments {
      id
      name
      deployType
      environmentType
      route
      updated
    }
  }
}

query EnvironmentInfo($name: String!, $project: Int!) {
  environmentByName(name: $name, project: $project) {
    id
    name
    deployType
    deployBaseRef
    environmentType
    openshiftProjectName
    created
    updated
    route
    routes
    services {
      id
      name
      type
      replicas
      updated
    }
    facts(keyFacts: true, limit: 100) {
      id
      name
      value
      source
      category
      service
    }
  }
}
